### ISSUE TITLE
Add Support for paper-plugin.yml

### ISSUE THREAD

**Issue by 4drian3d** [Minecrell/plugin-yml#27]
Recently [Paper introduced a new concept of Paper-exclusive plugins](https://github.com/PaperMC/Paper/pull/8108), and this brings with it a new file to declare those plugins, called [paper-plugin.yml](https://docs.papermc.io/paper/dev/getting-started/paper-plugins#how-do-i-use-them)
It would be nice to add support for this file

**Comment by stephan-gh** [comment]
I think this would mainly just involve [duplicating the Bukkit part of the plugin](https://github.com/Minecrell/plugin-yml/tree/master/src/main/kotlin/net/minecrell/pluginyml/bukkit) with an adjusted `PaperPluginDescription` that matches the `paper-plugin.yml` format. While it seems to have lots of similarities to the Bukkit `plugin.yml` it's probably still not worth sharing any code between them due to the subtle differences. Contributions would be very welcome :)

**Comment by Rattlyy** [comment]
idea: [Loaders](https://docs.papermc.io/paper/dev/getting-started/paper-plugins#loaders) can dynamically add any dependency, even the non maven-central ones. During the yml generation part, generate a class that adds every library to the context through a static method that you call in the bootstrapper.
